sonar.projectKey=precious0612_sonar_demo
sonar.organization=precious0612
sonar.host.url=https://sonarcloud.io

# 你的生产代码目录
sonar.sources=py-app,rust-app/src

# 你的测试目录/文件（你现在 Python 测试就在 py-app 下）
sonar.tests=py-app

# 排除 Rust target、venv、pycache
sonar.exclusions=**/rust-app/target/**,**/.venv/**,**/__pycache__/**

# Python 覆盖率（你会在 repo 根生成 coverage.xml 或者指定路径）
sonar.python.coverage.reportPaths=coverage.xml

# Rust 覆盖率（你需要在 CI 里生成 rust_coverage/lcov.info）
sonar.rust.lcov.reportPaths=rust_coverage/lcov.info